version: '3.8'

services:
  web:
    build:
      context: .
    container_name: codeigniter-app
    ports:
      - "80:80"            # Mapping host:container port yang benar
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: codeigniter-db
    restart: always
    environment:
      MYSQL_DATABASE: ci_db
      MYSQL_USER: ci_user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
