name: CI Pipeline

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  php-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: db_absensi_test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, pdo, pdo_mysql, mysqli
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist

      - name: Run Unit Tests
        run: composer run-script test

  # docker-build-and-push:
  #   runs-on: ubuntu-latest
  #   needs: php-test

    # steps:
    #   - uses: actions/checkout@v4

    #   - uses: docker/setup-buildx-action@v3

    #   - name: Login to ACR
    #     uses: docker/login-action@v3
    #     with:
    #       registry: ${{ secrets.AZURE_REGISTRY_URL }}
    #       username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
    #       password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    #   - name: Build and Push
    #     run: |
    #       docker build -t ${{ secrets.AZURE_REGISTRY_URL }}/myapp:latest .
    #       docker push ${{ secrets.AZURE_REGISTRY_URL }}/myapp:latest
